# SCSS-Lint 0.33.0

# 対象ファイル
scss_files: 'app/assets/stylesheets/**/*.scss'

# 各Linterの詳細は公式ドキュメントを参照
# https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md
linters:

  # bangキーワードの記述方法を統一する
  # (good) color: #000 !important;
  #  (bad) color: #000!important;
  BangFormat:
    enabled: true
    # 「!」記号の前にスペースを空ける
    space_before_bang: true
    # 「!」記号の後にスペースを空けない
    space_after_bang: false

  # borderプロパティの指定方法を統一する
  # (good) border: 0;
  #  (bad) border: none;
  BorderZero:
    enabled: true
    convention: zero

  # カラーキーワードの使用を許可しない
  # (good) color: #008000;
  #  (bad) color: green;
  ColorKeyword:
    enabled: true

  # 色を指定するときは必ず変数を使用する
  # TODO: scss-lint 0.33.0 では指定しても有効になってないかも
  ColorVariable:
    enabled: true

  # コメントは必ずSCSSコメントを使用する
  # (good) // コメントです。
  #  (bad) /* コメントです。 */
  Comment:
    enabled: true

  # Compassの使用を前提としたLinterを無効にする
  Compass::*:
    enabled: false

  DebugStatement:
    enabled: true

  # 1つのルールセット内でのプロパティの宣言順を以下で統一する
  # (1) @extend
  # (2) ブロックを含まない@include
  # (3) プロパティ
  # (4) ブロックを含む@include
  # (5) ネストしたルールセット
  DeclarationOrder:
    enabled: true

  # 1つのルールセット内でのプロパティの重複宣言を許可しない
  DuplicateProperty:
    enabled: true

  # @elseステートメントを直前の波カッコと同じ行に記述する
  ElsePlacement:
    enabled: true
    style: same_line

  # ブロック間を空行で空ける
  EmptyLineBetweenBlocks:
    enabled: true
    # 1行のブロックの場合は空行で空けても空けなくてもよい
    ignore_single_line_blocks: true

  # 空のルールセットを許可しない
  EmptyRule:
    enabled: true

  # ファイル最終行の改行が存在するかを統一する
  FinalNewline:
    enabled: true
    # ファイル最終行の改行が存在するようにする
    present: true

  # 色の16進数が省略可能な場合の指定方法を統一する
  # (good) color: #fff;
  #  (bad) color: #ffffff;
  HexLength:
    enabled: true
    # 省略する
    style: short

  # 色の16進数に含まれるアルファベットの大文字・小文字を統一する
  HexNotation:
    enabled: true
    # 小文字で統一する
    style: lowercase

  # 色の16進数の指定がvalidかをチェックする
  # (good) color: #fff;
  #  (bad) color: #ff;
  HexValidation:
    enabled: true

  # IDセレクタの使用を許可しない
  IdSelector:
    enabled: true

  # !important宣言を許可しない
  # TODO: scss-lint 0.33.0 では指定しても有効になってないかも
  ImportantRule:
    enabled: true

  # インポート文の記述方法を統一する
  ImportPath:
    enabled: true
    # インポート文のパス指定にパーシャル名のアンダースコアを含まない
    # (good) @import "foo/bar";
    #  (bad) @import "foo/_bar";
    leading_underscore: false
    # インポート文のパス指定に拡張子を含まない
    # (good) @import "foo/bar";
    #  (bad) @import "foo/bar.scss";
    filename_extension: false

  # インデントのルールを統一する
  Indentation:
    enabled: true
    # ネストされてないルールセットの自由なインデントを許可しない
    # TODO: scss-lint 0.33.0 では指定しても有効になってないかも
    allow_non_nested_indentation: false
    # インデントは空白文字
    character: space
    # インデントは2文字分
    width: 2

  # 小数点の時のゼロを省略しない
  # (good) 0.5
  #  (bad) .5
  LeadingZero:
    enabled: true
    style: include_zero

  # 同じセレクタは1つにまとめる
  MergeableSelector:
    enabled: true
    # 子セレクタも必ずネストを使ってまとめる
    force_nesting: true

  # 変数、関数、ミックスイン、プレースホルダーセレクタの命名規則を統一する
  NameFormat:
    enabled: true
    convention: '^[a-zA-Z_][-a-zA-Z0-9_]*$'

  # ネストの深さを制限する
  NestingDepth:
    enabled: true
    max_depth: 3

  # プロパティのソート順を統一する
  PropertySortOrder:
    enabled: true
    # プロパティのソート順をアルファベット順にする
    order: null
    # 仕様化されてないプロパティもソート順を統一する
    ignore_unspecified: false
    # プロパティ間の空行を許可しない
    separate_groups: false

  # セレクタの命名規則を統一する
  SelectorFormat:
    enabled: true
    convention: '^[a-zA-Z][-a-zA-Z0-9]*$'
    # クラス名はSUIT CSSの命名規則に準拠、`c-`プレフィックスは独自拡張
    # https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md
    class_convention: '^([A-Z]|u-|is-|c-)[-a-zA-Z0-9]*$'

  # セレクタに要素を含まない
  QualifyingElement:
    enabled: true
    # 属性セレクタの場合は許可する
    # (good) [href="foo"] {}
    #        a[href="foo"] {}
    allow_element_with_attribute: true
    # クラスセレクタの場合は許可しない
    # (good) .foo {}
    #  (bad) a.foo {}
    allow_element_with_class: false
    # IDセレクタの場合は許可しない
    # (good) #foo {}
    #  (bad) a#foo {}
    allow_element_with_id: false

  # セレクタ（ネスト）の深さを制限する
  # (good) .one .two .three {}
  #  (bad) .one .two .three .four {}
  SelectorDepth:
    enabled: true
    max_depth: 3

  Shorthand:
    enabled: false

  # セレクタは1行に1つだけ指定する
  # (good) .foo p,
  #        h1.bar {
  #          ...
  #        }
  #  (bad) .foo p, h1.bar {
  #          ...
  #        }
  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: false

  SpaceBeforeBrace:
    allow_single_line_padding: true

  StringQuotes:
    style: double_quotes

  # 整数に不要な小数点を付けない
  # (good) 1px
  #  (bad) 1.0px
  UnnecessaryMantissa:
    enabled: true

  # ベンダープレフィックスを手動で書かない
  VendorPrefixes:
    enabled: true
    # Autoprefixerが自動で付けるプロパティ等を対象とする
    # https://github.com/causes/scss-lint/blob/master/data/prefixed-identifiers/base.txt
    identifier_list: base
    include: []
    exclude: []

  # ゼロに単位を付けない
  # (good) 0
  #  (bad) 0px
  ZeroUnit:
    enabled: true
