# SCSS-Lint 0.33.0

# 対象ファイル
scss_files: 'app/assets/stylesheets/**/*.scss'

# 用語説明
#
# .foo {
#   color: #fff;
# }
#
# .foo         - セレクタ
# 波カッコ部分 - 宣言ブロック
# color: #fff; - 宣言
# color        - プロパティ
# #fff         - 値
# 上記すべて   - ルールセット

# 各Linterの詳細は公式ドキュメントを参照
# https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md
linters:

  # bangキーワードの記述方法を統一する
  # (good) color: #000 !important;
  #  (bad) color: #000!important;
  BangFormat:
    enabled: true
    # 「!」記号の前にスペースを空ける
    space_before_bang: true
    # 「!」記号の後にスペースを空けない
    space_after_bang: false

  # borderプロパティの値がゼロの時の指定方法を統一する
  # (good) border: 0;
  #  (bad) border: none;
  BorderZero:
    enabled: true
    convention: zero

  # カラーキーワードの値の使用を許可しない
  # (good) color: #008000;
  #  (bad) color: green;
  ColorKeyword:
    enabled: true

  # 色の値を指定するときは必ず変数を使用する
  # FIXME: scss-lint 0.33.0 では指定しても有効になってないかも
  ColorVariable:
    enabled: true

  # コメントは必ずSCSSコメントを使用する
  # (good) // コメントです。
  #  (bad) /* コメントです。 */
  Comment:
    enabled: true

  # Compassの使用を前提としたLinterを無効にする
  Compass::*:
    enabled: false

  DebugStatement:
    enabled: true

  # 宣言ブロック内での宣言順を以下で統一する
  # (1) @extend
  # (2) ブロックを含まない@include
  # (3) プロパティ
  # (4) ブロックを含む@include
  # (5) ネストしたルールセット
  DeclarationOrder:
    enabled: true

  # 宣言ブロック内でのプロパティの重複を許可しない
  DuplicateProperty:
    enabled: true

  # @elseステートメントを直前の波カッコと同じ行に記述する
  ElsePlacement:
    enabled: true
    style: same_line

  # ルールセット間を空行で空ける
  EmptyLineBetweenBlocks:
    enabled: true
    # 宣言ブロックが1行の場合はルールセット間を空行で空けても空けなくてもよい
    ignore_single_line_blocks: true

  # 宣言の記述されていない空のルールセットを許可しない
  #  (bad) .foo {
  #        }
  EmptyRule:
    enabled: true

  # ファイル最終行の改行が存在するかを統一する
  FinalNewline:
    enabled: true
    # ファイル最終行の改行が存在するようにする
    present: true

  # 色の16進数の値が省略可能な場合の記述方法を統一する
  # (good) color: #fff;
  #  (bad) color: #ffffff;
  HexLength:
    enabled: true
    # 省略可能な場合は省略する
    style: short

  # 色の16進数の値に含まれるアルファベットの大文字・小文字を統一する
  HexNotation:
    enabled: true
    # 小文字で統一する
    style: lowercase

  # 色の16進数の値がvalidかをチェックする
  # (good) color: #fff;
  #  (bad) color: #ff;
  HexValidation:
    enabled: true

  # IDセレクタの使用を許可しない
  IdSelector:
    enabled: true

  # !important宣言を許可しない
  # FIXME: scss-lint 0.33.0 では指定しても有効になってないかも
  ImportantRule:
    enabled: true

  # インポート文の指定方法を統一する
  ImportPath:
    enabled: true
    # インポート文のパス指定にパーシャル名のアンダースコアを含まない
    # (good) @import "foo/bar";
    #  (bad) @import "foo/_bar";
    leading_underscore: false
    # インポート文のパス指定に拡張子を含まない
    # (good) @import "foo/bar";
    #  (bad) @import "foo/bar.scss";
    filename_extension: false

  # インデントのルールを統一する
  Indentation:
    enabled: true
    # ネストされてないルールセットの自由なインデントを許可しない
    # FIXME: scss-lint 0.33.0 では指定しても有効になってないかも
    allow_non_nested_indentation: false
    # インデントは空白文字
    character: space
    # インデントは2文字分
    width: 2

  # 小数点の値のゼロを省略しない
  # (good) 0.5
  #  (bad) .5
  LeadingZero:
    enabled: true
    style: include_zero

  # 同じセレクタは1つにまとめる
  MergeableSelector:
    enabled: true
    # 子・子孫セレクタも必ずネストを使ってまとめる
    force_nesting: true

  # 変数、関数、ミックスイン、プレースホルダーセレクタの命名規則を統一する
  NameFormat:
    enabled: true
    convention: '^[a-zA-Z_][-a-zA-Z0-9_]*$'

  # ネストの深さを制限する
  NestingDepth:
    enabled: true
    max_depth: 3

  # @extendの対象をプレースホルダーセレクタのみに制限する
  PlaceholderInExtend:
    enabled: true

  # 宣言ブロック内でのプロパティの宣言数を制限する
  # FIXME: scss-lint 0.33.0 では指定しても有効になってないかも
  PropertyCount:
    enabled: true
    # ネストされた宣言は含まない
    include_nested: false
    # プロパティの宣言数は最大10個
    max_properties: 10

  # プロパティのソート順を統一する
  PropertySortOrder:
    enabled: true
    # プロパティのソート順をアルファベット順にする
    order: null
    # 仕様化されてないプロパティもソート順の統一に含む
    ignore_unspecified: false
    # 視覚的なグループを目的としたプロパティ間の空行を許可しない
    separate_groups: false

  # 未知のプロパティ名を警告する（ベンダープレフィックスのプロパティは含まない）
  PropertySpelling:
    enabled: true
    # 未知ではないプロパティ名の指定
    extra_properties: []

  # セレクタに要素セレクタを含まない
  QualifyingElement:
    enabled: true
    # 属性セレクタの場合は許可する
    # (good) [href="foo"] {}
    #        a[href="foo"] {}
    allow_element_with_attribute: true
    # クラスセレクタの場合は許可しない
    # (good) .foo {}
    #  (bad) a.foo {}
    allow_element_with_class: false
    # IDセレクタの場合は許可しない
    # (good) #foo {}
    #  (bad) a#foo {}
    allow_element_with_id: false

  # セレクタ（ネスト）の深さを制限する
  # (good) .one .two .three {}
  #  (bad) .one .two .three .four {}
  SelectorDepth:
    enabled: true
    max_depth: 3

  # セレクタの命名規則を統一する
  SelectorFormat:
    enabled: true
    convention: '^[a-zA-Z][-a-zA-Z0-9]*$'
    # クラス名はSUIT CSSの命名規則に準拠、`c-`プレフィックスは独自拡張
    # https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md
    class_convention: '^([A-Z]|u-|is-|c-)[-a-zA-Z0-9]*$'

  # 値の指定でショートハンド記法が使える場合は使用する
  # (good) margin: 1px;
  #  (bad) margin: 1px 1px 1px 1px;
  Shorthand:
    enabled: true

  # 宣言ブロック内のプロパティは1行につき1つのみの記述に制限する
  SingleLinePerProperty:
    enabled: true
    # ルールセットを1行で書く場合は複数指定を許容する
    # (good) .foo { margin: 1px; color: red; }
    allow_single_line_rule_sets: true

  # セレクタは1行につき1つのみ指定する
  # (good) .foo p,
  #        h1.bar {
  #          ...
  #        }
  #  (bad) .foo p, h1.bar {
  #          ...
  #        }
  SingleLinePerSelector:
    enabled: true

  # コンマの後にスペースを1つ入れる
  # (good) color: rgba(0, 0, 0, 0);
  #  (bad) color: rgba(0,0,0,0);
  SpaceAfterComma:
    enabled: true

  # プロパティのコロンの後にスペースを1つ入れる
  # (good) margin: 0;
  #  (bad) margin:0;
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  # プロパティとコロンの間にスペースを入れない
  # (good) margin: 0;
  #  (bad) margin : 0;
  SpaceAfterPropertyName:
    enabled: true

  # セレクタと波カッコの間にスペースを1つ入れる
  # (good) p {
  #          ...
  #        }
  #  (bad) p{
  #          ...
  #        }
  SpaceBeforeBrace:
    enabled: true
    style: space
    # ルールセットを1行で書く場合は複数スペースを許容する
    # (good) .foo    { margin: 1px; }
    #        .foobar { margin: 1px; }
    allow_single_line_padding: true

  # 丸括弧の内側にスペースを入れない
  # (good) color: rgba(0, 0, 0, 0);
  #  (bad) color: rgba( 0, 0, 0, 0 );
  SpaceBetweenParens:
    enabled: true
    spaces: 0

  # 文字列のクォーテーションはダブルクォーテーションを使用する
  # (good) content: "hello";
  #  (bad) content: 'hello';
  StringQuotes:
    enabled: true
    style: double_quotes

  # 宣言末尾のセミコロンは省略せずスペースも空けない
  # (good) color: #fff;
  #  (bad) color: #fff
  #  (bad) color: #fff ;
  TrailingSemicolon:
    enabled: true

  # 値の整数に不要な小数点を付けない
  # (good) 1px
  #  (bad) 1.0px
  UnnecessaryMantissa:
    enabled: true

  # ベンダープレフィックスを手動で書かない
  VendorPrefixes:
    enabled: true
    # Autoprefixerが自動で付けるプロパティ等を対象とする
    # https://github.com/causes/scss-lint/blob/master/data/prefixed-identifiers/base.txt
    identifier_list: base
    include: []
    exclude: []

  # 値のゼロに単位を付けない
  # (good) 0
  #  (bad) 0px
  ZeroUnit:
    enabled: true
