
# SCSS-Lintの対象ファイル
scss_files: 'app/assets/stylesheets/**/*.scss'

linters:

  # borderプロパティの指定方法を統一する
  BorderZero:
    enabled: true
    # good: `border: 0;`
    #  bad: `border: none;`
    convention: zero

  # カラーキーワードの使用を許可しない
  # good: `color: #ffffff;`
  #  bad: `color: white;`
  ColorKeyword:
    enabled: true

  # 1つのルールセット内でのプロパティの宣言順を守る
  # 宣言順: (1) @extend
  #         (2) ブロックを含まない@include
  #         (3) プロパティ
  #         (4) ブロックを含む@include
  #         (5) ネストしたルールセット
  DeclarationOrder:
    enabled: true

  # 1つのルールセット内でのプロパティの重複宣言を許可しない
  DuplicateProperty:
    enabled: true

  # ブロック間を空行で空ける
  EmptyLineBetweenBlocks:
    enabled: true
    # 1行のブロックの場合は空行で空けても空けなくてもよい
    ignore_single_line_blocks: true

  # 色の16進数が省略可能な場合の指定方法を統一する
  HexLength:
    enabled: true
    # good: `color: #fff;`
    #  bad: `color: #ffffff;`
    style: short

  NameFormat:
    enabled: true
    convention: '^[a-z_][-a-zA-Z0-9_]*$'

  SelectorFormat:
    enabled: true
    convention: '^[a-zA-Z0-9][-a-zA-Z0-9]*$'
    # クラス名がSUIT CSSの命名規則に準拠するための正規表現
    # https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md
    class_convention: '^([A-Z]|u-|is-)[-a-zA-Z0-9]*$'

  PropertySortOrder:
    enabled: true
    # プロパティのソート順をアルファベット順にする
    order: null
    # 仕様化されてないプロパティもソート順を守る
    ignore_unspecified: false
    # プロパティ間の空行を許可しない
    separate_groups: false

  # 小数点の時のゼロを省略しない
  # good: `0.5`
  #  bad: `.5`
  LeadingZero:
    enabled: true
    style: include_zero

  ImportPath:
    enabled: true
    # インポート文のパス指定にパーシャル名のアンダースコアを含まない
    # good: `@import "foo/bar";`
    #  bad: `@import "foo/_bar";`
    leading_underscore: false
    # インポート文のパス指定に拡張子を含まない
    # good: `@import "foo/bar";`
    #  bad: `@import "foo/bar.scss";`
    filename_extension: false

  Indentation:
    enabled: true
    # インデントは空白文字
    character: space
    # インデントは2文字分
    width: 2

  Comment:
    enabled: false

  # セレクター（ネスト）の深さを制限する
  # good: `.one .two .three {}`
  #  bad: `.one .two .three .four {}`
  SelectorDepth:
    enabled: true
    max_depth: 3

  Shorthand:
    enabled: false

  SpaceAfterComma:
    enabled: false

  SpaceBeforeBrace:
    allow_single_line_padding: true

  StringQuotes:
    style: double_quotes

  MergeableSelector:
    force_nesting: false

  # 整数に不要な小数点を付けない
  # good: `1px`
  #  bad: `1.0px`
  UnnecessaryMantissa:
    enabled: true

  # ベンダープレフィックスを手動で書かない
  VendorPrefixes:
    enabled: true
    # Autoprefixerが自動で付けるプロパティ等を対象とする
    # https://github.com/causes/scss-lint/blob/master/data/prefixed-identifiers/base.txt
    identifier_list: base
    include: []
    exclude: []

  # ゼロに単位を付けない
  # good: `0`
  #  bad: `0px`
  ZeroUnit:
    enabled: true
