source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'slim', '~> 2.0.0'
gem 'slim-rails', '~> 2.0.1'
gem 'kramdown', '~> 1.1.0'
