# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf0c287a6d40d0648b729a2ee231c45ecea54bc9a4a60e6e6e56eb54b6b24f6030008401a61017d7662b768cf6a553720a5553a86da6feebd37ee489453e626

test:
  secret_key_base: 751137e1208fe0e47f5addbfba28b6f55b2d3d2de425cf69ee5c95c5474561402686dad703af3de5fff19c408ed89db71c448f2d2803089d8d1fa869862fab47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
