name: Visual Regression Testing

env:
  CI: true
  NODE_VERSION: 12.x
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  VRT_NOTIFY_GITHUB_CLIENT_ID: ${{ secrets.VRT_NOTIFY_GITHUB_CLIENT_ID }}
  VRT_PUBLISH_S3_BUCKET_NAME: ${{ secrets.VRT_PUBLISH_S3_BUCKET_NAME }}

on:
  - push

jobs:
  vrt:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install node modules
        run: npm ci

      - name: Run tests
        run: npm run ci:vrt
